"""Production-ready review webhook server.

When running in the cloud the pipeline exposes a FastAPI app on a configurable
port (default 8742). Approve / edit links in notification emails point to this
server at the public hostname set via PIPELINE_PUBLIC_URL.

Architecture
------------
::

    ┌─────────────┐   email with links   ┌──────────┐
    │   Pipeline  │ ──────────────────►  │  Creator │
    │  (FastAPI)  │                      │ (phone)  │
    │             │ ◄── GET /approve?token=xxx ──── │
    └──────────┬──┘                      └──────────┘
               │  asyncio.Queue
               ▼
          ReviewGate.poll_until_action()

Token lifecycle
---------------
* Generated by ``ReviewToken.create()`` — a random URL-safe string stored in
  an in-process dict keyed by video_id.
* Single-use: consumed on first valid tap, then deleted.
* Expire after ``TOKEN_TTL_SECONDS`` (default 7 days).

Configuration
-------------
Set in .env::

    PIPELINE_PUBLIC_URL=https://yourapp.railway.app   # no trailing slash
    REVIEW_SERVER_PORT=8742                            # optional, default 8742

The FastAPI app is started once alongside the pipeline process via
``asyncio.create_task(start_review_server())``.  It shares the same event loop
so the Queue hand-off is zero-copy.
"""

from __future__ import annotations

import asyncio
import logging
import os
import secrets
import time
from dataclasses import dataclass, field
from typing import Literal, Optional

logger = logging.getLogger(__name__)

TOKEN_TTL_SECONDS: int = 7 * 24 * 3600   # 7 days

# ---------------------------------------------------------------------------
# In-process token store
# ---------------------------------------------------------------------------

@dataclass
class _PendingReview:
    video_id: str
    gate_type: Literal["script", "final"]
    token: str
    created_at: float
    queue: asyncio.Queue  # type: ignore[type-arg]   # receives "approve" | "edit"


_pending: dict[str, _PendingReview] = {}   # token → PendingReview


def create_review_token(
    video_id: str,
    gate_type: Literal["script", "final"],
    queue: "asyncio.Queue[str]",
) -> str:
    """Register a new review and return a single-use token.

    Args:
        video_id: Pipeline video identifier.
        gate_type: ``"script"`` or ``"final"``.
        queue: Asyncio queue that receives the creator's action string.

    Returns:
        A URL-safe token string.
    """
    token = secrets.token_urlsafe(32)
    _pending[token] = _PendingReview(
        video_id=video_id,
        gate_type=gate_type,
        token=token,
        created_at=time.time(),
        queue=queue,
    )
    logger.debug("Review token created: video_id=%s gate=%s", video_id, gate_type)
    return token


def _resolve_token(token: str) -> Optional[_PendingReview]:
    """Look up and validate a token; return None if absent or expired."""
    review = _pending.get(token)
    if review is None:
        return None
    if time.time() - review.created_at > TOKEN_TTL_SECONDS:
        del _pending[token]
        return None
    return review


def get_review_urls(token: str) -> tuple[str, str]:
    """Return ``(approve_url, edit_url)`` for the given token.

    Uses ``PIPELINE_PUBLIC_URL`` from the environment.

    Args:
        token: Token returned by :func:`create_review_token`.

    Returns:
        Tuple of ``(approve_url, edit_url)``.
    """
    base = os.environ.get("PIPELINE_PUBLIC_URL", "http://localhost:8742").rstrip("/")
    return (
        f"{base}/review/approve?token={token}",
        f"{base}/review/edit?token={token}",
    )


# ---------------------------------------------------------------------------
# FastAPI application
# ---------------------------------------------------------------------------

def build_review_app() -> "fastapi.FastAPI":  # type: ignore[name-defined]
    """Build and return the FastAPI review webhook app."""
    from fastapi import FastAPI, HTTPException, Query  # type: ignore[import-untyped]
    from fastapi.responses import HTMLResponse  # type: ignore[import-untyped]

    app = FastAPI(title="AI YouTube Pipeline — Review Webhook", docs_url=None)

    @app.get("/health")
    async def health() -> dict:  # type: ignore[type-arg]
        return {"status": "ok", "pending_reviews": len(_pending)}

    @app.get("/review/approve", response_class=HTMLResponse)
    async def approve(token: str = Query(...)) -> str:
        review = _resolve_token(token)
        if review is None:
            raise HTTPException(status_code=404, detail="Token not found or expired.")
        del _pending[token]   # single-use
        await review.queue.put("approve")
        logger.info("Review approved via webhook: video_id=%s", review.video_id)
        return _HTML_APPROVED

    @app.get("/review/edit", response_class=HTMLResponse)
    async def request_edit(token: str = Query(...)) -> str:
        review = _resolve_token(token)
        if review is None:
            raise HTTPException(status_code=404, detail="Token not found or expired.")
        del _pending[token]   # single-use
        await review.queue.put("edit")
        logger.info("Edit requested via webhook: video_id=%s", review.video_id)
        return _HTML_EDIT

    return app


async def start_review_server(port: Optional[int] = None) -> None:
    """Start the review webhook server using asyncio's native HTTP server.

    Designed to be launched as a background task at pipeline startup::

        asyncio.create_task(start_review_server())

    Uses ``asyncio.start_server`` directly — no uvicorn dependency, no event
    loop conflicts, cancels cleanly.

    Args:
        port: Override the port (used in tests).
    """
    resolved_port = port or int(os.environ.get("REVIEW_SERVER_PORT", "8742"))
    public_url = os.environ.get("PIPELINE_PUBLIC_URL", f"http://localhost:{resolved_port}")

    async def _handle(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
        try:
            raw = await reader.read(4096)
            if not raw:
                return
            first_line = raw.split(b"\r\n")[0].decode("utf-8", errors="replace")
            parts = first_line.split(" ")
            if len(parts) < 2:
                return

            path = parts[1]          # e.g. /review/approve?token=xxx
            from urllib.parse import urlparse, parse_qs  # noqa: PLC0415
            parsed = urlparse(path)
            params = parse_qs(parsed.query)
            token  = params.get("token", [""])[0]

            if parsed.path in ("/review/approve", "/review/edit"):
                review = _resolve_token(token)
                if review is None:
                    _write_http(writer, 404, "text/html", b"<h1>Token not found or expired.</h1>")
                else:
                    del _pending[token]
                    action = "approve" if parsed.path == "/review/approve" else "edit"
                    # Put on queue from the running event loop
                    loop = asyncio.get_event_loop()
                    loop.call_soon_threadsafe(review.queue.put_nowait, action)
                    html = _HTML_APPROVED if action == "approve" else _HTML_EDIT
                    _write_http(writer, 200, "text/html", html.encode())
                    logger.info("Review action '%s' received for video_id=%s", action, review.video_id)

            elif parsed.path == "/health":
                body = f'{{"status":"ok","pending":{len(_pending)}}}'.encode()
                _write_http(writer, 200, "application/json", body)
            else:
                _write_http(writer, 404, "text/plain", b"Not found")

        except Exception as exc:  # noqa: BLE001
            logger.debug("Review server handler error: %s", exc)
        finally:
            try:
                writer.close()
                await writer.wait_closed()
            except Exception:  # noqa: BLE001
                pass

    server = await asyncio.start_server(_handle, "0.0.0.0", resolved_port)
    logger.info(
        "Review webhook server listening on port %d  (public: %s)",
        resolved_port, public_url,
    )
    async with server:
        await server.serve_forever()


def _write_http(
    writer: asyncio.StreamWriter,
    status: int,
    content_type: str,
    body: bytes,
) -> None:
    """Write a minimal HTTP/1.1 response."""
    reason = {200: "OK", 404: "Not Found"}.get(status, "")
    header = (
        f"HTTP/1.1 {status} {reason}\r\n"
        f"Content-Type: {content_type}; charset=utf-8\r\n"
        f"Content-Length: {len(body)}\r\n"
        f"Connection: close\r\n"
        f"\r\n"
    ).encode()
    writer.write(header + body)


# ---------------------------------------------------------------------------
# HTML response pages
# ---------------------------------------------------------------------------

_HTML_APPROVED = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Script Approved</title>
<style>
  body{font-family:-apple-system,sans-serif;display:flex;align-items:center;
       justify-content:center;min-height:100vh;margin:0;background:#f0fdf4}
  .card{background:#fff;border-radius:16px;padding:40px;text-align:center;
        box-shadow:0 4px 24px rgba(0,0,0,.08);max-width:420px;width:90%}
  .icon{font-size:72px;margin-bottom:16px}
  h1{color:#16a34a;font-size:26px;margin:0 0 10px}
  p{color:#6b7280;margin:0;font-size:16px;line-height:1.5}
</style></head>
<body><div class="card">
  <div class="icon">✅</div>
  <h1>Script Approved!</h1>
  <p>The pipeline will continue to narration&nbsp;generation automatically.</p>
</div></body></html>"""

_HTML_EDIT = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Edit Requested</title>
<style>
  body{font-family:-apple-system,sans-serif;display:flex;align-items:center;
       justify-content:center;min-height:100vh;margin:0;background:#fffbeb}
  .card{background:#fff;border-radius:16px;padding:40px;text-align:center;
        box-shadow:0 4px 24px rgba(0,0,0,.08);max-width:420px;width:90%}
  .icon{font-size:72px;margin-bottom:16px}
  h1{color:#d97706;font-size:26px;margin:0 0 10px}
  p{color:#6b7280;margin:0;font-size:16px;line-height:1.5}
</style></head>
<body><div class="card">
  <div class="icon">✏️</div>
  <h1>Edit Requested</h1>
  <p>The pipeline will regenerate the script.<br>
     You can add notes in your Notion&nbsp;calendar.</p>
</div></body></html>"""


__all__ = [
    "create_review_token",
    "get_review_urls",
    "start_review_server",
]
