"""Production-ready review webhook server.

When running in the cloud the pipeline exposes a FastAPI app on a configurable
port (default 8742). Approve / edit links in notification emails point to this
server at the public hostname set via PIPELINE_PUBLIC_URL.

Architecture
------------
::

    ┌─────────────┐   email with links   ┌──────────┐
    │   Pipeline  │ ──────────────────►  │  Creator │
    │  (FastAPI)  │                      │ (phone)  │
    │             │ ◄── GET /approve?token=xxx ──── │
    └──────────┬──┘                      └──────────┘
               │  asyncio.Queue
               ▼
          ReviewGate.poll_until_action()

Token lifecycle
---------------
* Generated by ``ReviewToken.create()`` — a random URL-safe string stored in
  an in-process dict keyed by video_id.
* Single-use: consumed on first valid tap, then deleted.
* Expire after ``TOKEN_TTL_SECONDS`` (default 7 days).

Configuration
-------------
Set in .env::

    PIPELINE_PUBLIC_URL=https://yourapp.railway.app   # no trailing slash
    REVIEW_SERVER_PORT=8742                            # optional, default 8742

The FastAPI app is started once alongside the pipeline process via
``asyncio.create_task(start_review_server())``.  It shares the same event loop
so the Queue hand-off is zero-copy.
"""

from __future__ import annotations

import asyncio
import logging
import os
import secrets
import time
from dataclasses import dataclass, field
from typing import Literal, Optional

logger = logging.getLogger(__name__)

TOKEN_TTL_SECONDS: int = 7 * 24 * 3600   # 7 days

# ---------------------------------------------------------------------------
# In-process token store
# ---------------------------------------------------------------------------

@dataclass
class _PendingReview:
    video_id: str
    gate_type: Literal["script", "final"]
    token: str
    created_at: float
    queue: asyncio.Queue  # type: ignore[type-arg]   # receives "approve" | "edit"


_pending: dict[str, _PendingReview] = {}   # token → PendingReview

# Temp media files served via /media/{name} for Instagram Reel uploads
_media_files: dict[str, str] = {}   # filename → local file path


def register_media_file(filename: str, local_path: str) -> str:
    """Register a local file to be served via the review server's /media/ endpoint.

    Args:
        filename: The filename to serve it as (e.g., "reel_abc123.mp4").
        local_path: Absolute path to the file on disk.

    Returns:
        The public URL path (combine with PIPELINE_PUBLIC_URL to get full URL).
    """
    _media_files[filename] = local_path
    return f"/media/{filename}"


def unregister_media_file(filename: str) -> None:
    """Remove a file from the media serving registry."""
    _media_files.pop(filename, None)


def create_review_token(
    video_id: str,
    gate_type: Literal["script", "final"],
    queue: "asyncio.Queue[str]",
) -> str:
    """Register a new review and return a single-use token.

    Args:
        video_id: Pipeline video identifier.
        gate_type: ``"script"`` or ``"final"``.
        queue: Asyncio queue that receives the creator's action string.

    Returns:
        A URL-safe token string.
    """
    token = secrets.token_urlsafe(32)
    _pending[token] = _PendingReview(
        video_id=video_id,
        gate_type=gate_type,
        token=token,
        created_at=time.time(),
        queue=queue,
    )
    logger.debug("Review token created: video_id=%s gate=%s", video_id, gate_type)
    return token


def _resolve_token(token: str) -> Optional[_PendingReview]:
    """Look up and validate a token; return None if absent or expired."""
    review = _pending.get(token)
    if review is None:
        return None
    if time.time() - review.created_at > TOKEN_TTL_SECONDS:
        del _pending[token]
        return None
    return review


def get_review_urls(token: str) -> tuple[str, str, str]:
    """Return ``(approve_url, edit_url, reject_url)`` for the given token.

    Uses ``PIPELINE_PUBLIC_URL`` from the environment.

    Args:
        token: Token returned by :func:`create_review_token`.

    Returns:
        Tuple of ``(approve_url, edit_url, reject_url)``.
    """
    base = os.environ.get("PIPELINE_PUBLIC_URL", "http://localhost:8742").rstrip("/")
    return (
        f"{base}/review/approve?token={token}",
        f"{base}/review/edit?token={token}",
        f"{base}/review/reject?token={token}",
    )


# ---------------------------------------------------------------------------
# FastAPI application
# ---------------------------------------------------------------------------

def build_review_app() -> "fastapi.FastAPI":  # type: ignore[name-defined]
    """Build and return the FastAPI review webhook app."""
    from fastapi import FastAPI, HTTPException, Query, Form  # type: ignore[import-untyped]
    from fastapi.responses import HTMLResponse  # type: ignore[import-untyped]

    app = FastAPI(title="AI YouTube Pipeline — Review Webhook", docs_url=None)

    @app.get("/health")
    async def health() -> dict:  # type: ignore[type-arg]
        return {"status": "ok", "pending_reviews": len(_pending)}

    @app.get("/review/approve", response_class=HTMLResponse)
    async def approve(token: str = Query(...)) -> str:
        review = _resolve_token(token)
        if review is None:
            raise HTTPException(status_code=404, detail="Token not found or expired.")
        del _pending[token]
        await review.queue.put("approve")
        logger.info("Review approved via webhook: video_id=%s", review.video_id)
        return _HTML_APPROVED

    @app.get("/review/edit", response_class=HTMLResponse)
    async def show_edit_form(token: str = Query(...)) -> str:
        """Show the edit form — token stays alive until the form is submitted."""
        review = _resolve_token(token)
        if review is None:
            raise HTTPException(status_code=404, detail="Token not found or expired.")
        return _build_edit_form_html(token)

    @app.post("/review/edit", response_class=HTMLResponse)
    async def submit_edit(
        token: str = Query(...),
        edit_instructions: str = Form(...),
    ) -> str:
        review = _resolve_token(token)
        if review is None:
            raise HTTPException(status_code=404, detail="Token not found or expired.")
        if not edit_instructions.strip():
            return _build_edit_form_html(token, error="Please enter your edit instructions.")
        del _pending[token]
        await review.queue.put(f"edit:{edit_instructions.strip()}")
        logger.info("Edit submitted via webhook: video_id=%s", review.video_id)
        return _HTML_EDIT_SUBMITTED

    @app.get("/review/reject", response_class=HTMLResponse)
    async def reject(token: str = Query(...)) -> str:
        review = _resolve_token(token)
        if review is None:
            raise HTTPException(status_code=404, detail="Token not found or expired.")
        del _pending[token]
        await review.queue.put("reject")
        logger.info("Script rejected via webhook: video_id=%s", review.video_id)
        return _HTML_REJECTED

    return app


async def start_review_server(port: Optional[int] = None) -> None:
    """Start the review webhook server using asyncio's native HTTP server.

    Designed to be launched as a background task at pipeline startup::

        asyncio.create_task(start_review_server())

    Uses ``asyncio.start_server`` directly — no uvicorn dependency, no event
    loop conflicts, cancels cleanly.

    Args:
        port: Override the port (used in tests).
    """
    resolved_port = port or int(os.environ.get("REVIEW_SERVER_PORT", "8742"))
    public_url = os.environ.get("PIPELINE_PUBLIC_URL", f"http://localhost:{resolved_port}")

    async def _handle(reader: asyncio.StreamReader, writer: asyncio.StreamWriter) -> None:
        try:
            # Read the full request (headers + body up to 32 KB)
            raw = await reader.read(32768)
            if not raw:
                return

            # Split head from body
            head_end = raw.find(b"\r\n\r\n")
            head_bytes = raw[:head_end] if head_end != -1 else raw
            body_bytes = raw[head_end + 4:] if head_end != -1 else b""

            first_line = head_bytes.split(b"\r\n")[0].decode("utf-8", errors="replace")
            parts = first_line.split(" ")
            if len(parts) < 2:
                return

            method = parts[0].upper()
            path = parts[1]
            from urllib.parse import urlparse, parse_qs, unquote_plus  # noqa: PLC0415
            parsed = urlparse(path)
            params = parse_qs(parsed.query)
            token = params.get("token", [""])[0]

            # ---- GET /review/approve ----
            if method == "GET" and parsed.path == "/review/approve":
                review = _resolve_token(token)
                if review is None:
                    _write_http(writer, 404, "text/html", b"<h1>Token not found or expired.</h1>")
                else:
                    del _pending[token]
                    loop = asyncio.get_event_loop()
                    loop.call_soon_threadsafe(review.queue.put_nowait, "approve")
                    _write_http(writer, 200, "text/html", _HTML_APPROVED.encode())
                    logger.info("Review approved for video_id=%s", review.video_id)

            # ---- GET /review/edit — show form ----
            elif method == "GET" and parsed.path == "/review/edit":
                review = _resolve_token(token)
                if review is None:
                    _write_http(writer, 404, "text/html", b"<h1>Token not found or expired.</h1>")
                else:
                    _write_http(writer, 200, "text/html", _build_edit_form_html(token).encode())

            # ---- POST /review/edit — submit form ----
            elif method == "POST" and parsed.path == "/review/edit":
                review = _resolve_token(token)
                if review is None:
                    _write_http(writer, 404, "text/html", b"<h1>Token not found or expired.</h1>")
                else:
                    # Parse application/x-www-form-urlencoded body
                    body_str = body_bytes.decode("utf-8", errors="replace")
                    form_params = parse_qs(body_str)
                    edit_text = form_params.get("edit_instructions", [""])[0]
                    edit_text = unquote_plus(edit_text).strip()

                    if not edit_text:
                        _write_http(
                            writer, 200, "text/html",
                            _build_edit_form_html(token, error="Please enter your edit instructions.").encode(),
                        )
                    else:
                        del _pending[token]
                        loop = asyncio.get_event_loop()
                        loop.call_soon_threadsafe(review.queue.put_nowait, f"edit:{edit_text}")
                        _write_http(writer, 200, "text/html", _HTML_EDIT_SUBMITTED.encode())
                        logger.info("Edit submitted for video_id=%s: %s", review.video_id, edit_text[:80])

            # ---- GET /review/reject ----
            elif method == "GET" and parsed.path == "/review/reject":
                review = _resolve_token(token)
                if review is None:
                    _write_http(writer, 404, "text/html", b"<h1>Token not found or expired.</h1>")
                else:
                    del _pending[token]
                    loop = asyncio.get_event_loop()
                    loop.call_soon_threadsafe(review.queue.put_nowait, "reject")
                    _write_http(writer, 200, "text/html", _HTML_REJECTED.encode())
                    logger.info("Script rejected for video_id=%s", review.video_id)

            elif parsed.path == "/health":
                body = f'{{"status":"ok","pending":{len(_pending)}}}'.encode()
                _write_http(writer, 200, "application/json", body)

            # ---- GET /media/{filename} — serve temp video files for Instagram ----
            elif parsed.path.startswith("/media/"):
                filename = parsed.path[len("/media/"):]
                if filename in _media_files:
                    file_path = _media_files[filename]
                    import pathlib as _pl  # noqa: PLC0415
                    fp = _pl.Path(file_path)
                    if fp.exists():
                        data = fp.read_bytes()
                        _write_http(writer, 200, "video/mp4", data)
                        logger.info("Served media file: %s (%d bytes)", filename, len(data))
                    else:
                        _write_http(writer, 404, "text/plain", b"File not found on disk")
                else:
                    _write_http(writer, 404, "text/plain", b"Unknown media file")

            else:
                _write_http(writer, 404, "text/plain", b"Not found")

        except Exception as exc:  # noqa: BLE001
            logger.debug("Review server handler error: %s", exc)
        finally:
            try:
                writer.close()
                await writer.wait_closed()
            except Exception:  # noqa: BLE001
                pass

    server = await asyncio.start_server(_handle, "0.0.0.0", resolved_port)
    logger.info(
        "Review webhook server listening on port %d  (public: %s)",
        resolved_port, public_url,
    )
    async with server:
        await server.serve_forever()


def _write_http(
    writer: asyncio.StreamWriter,
    status: int,
    content_type: str,
    body: bytes,
) -> None:
    """Write a minimal HTTP/1.1 response."""
    reason = {200: "OK", 404: "Not Found"}.get(status, "")
    header = (
        f"HTTP/1.1 {status} {reason}\r\n"
        f"Content-Type: {content_type}; charset=utf-8\r\n"
        f"Content-Length: {len(body)}\r\n"
        f"Connection: close\r\n"
        f"\r\n"
    ).encode()
    writer.write(header + body)


# ---------------------------------------------------------------------------
# HTML response pages
# ---------------------------------------------------------------------------

_HTML_APPROVED = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Script Approved</title>
<style>
  body{font-family:-apple-system,sans-serif;display:flex;align-items:center;
       justify-content:center;min-height:100vh;margin:0;background:#f0fdf4}
  .card{background:#fff;border-radius:16px;padding:40px;text-align:center;
        box-shadow:0 4px 24px rgba(0,0,0,.08);max-width:420px;width:90%}
  .icon{font-size:72px;margin-bottom:16px}
  h1{color:#16a34a;font-size:26px;margin:0 0 10px}
  p{color:#6b7280;margin:0;font-size:16px;line-height:1.5}
</style></head>
<body><div class="card">
  <div class="icon">✅</div>
  <h1>Script Approved!</h1>
  <p>The pipeline will continue to narration&nbsp;generation automatically.</p>
</div></body></html>"""


def _build_edit_form_html(token: str, error: str = "") -> str:
    """Return the edit form page, optionally with an inline error message."""
    error_html = (
        f'<p style="color:#dc2626;margin:0 0 12px;font-size:14px">{error}</p>'
        if error else ""
    )
    return f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Request Script Edit</title>
<style>
  body{{font-family:-apple-system,sans-serif;display:flex;align-items:center;
       justify-content:center;min-height:100vh;margin:0;background:#fffbeb}}
  .card{{background:#fff;border-radius:16px;padding:40px;
         box-shadow:0 4px 24px rgba(0,0,0,.08);max-width:520px;width:90%}}
  .icon{{font-size:56px;margin-bottom:12px;text-align:center}}
  h1{{color:#d97706;font-size:24px;margin:0 0 8px;text-align:center}}
  p.sub{{color:#6b7280;font-size:14px;margin:0 0 20px;text-align:center;line-height:1.5}}
  textarea{{width:100%;box-sizing:border-box;border:1.5px solid #d1d5db;border-radius:10px;
            padding:12px;font-size:15px;font-family:inherit;resize:vertical;
            min-height:120px;outline:none}}
  textarea:focus{{border-color:#d97706;box-shadow:0 0 0 3px rgba(217,119,6,.15)}}
  .btn{{display:block;width:100%;margin-top:14px;padding:14px;border:none;
        border-radius:10px;font-size:16px;font-weight:600;cursor:pointer;
        text-align:center}}
  .btn-submit{{background:#d97706;color:#fff}}
  .btn-submit:hover{{background:#b45309}}
</style></head>
<body><div class="card">
  <div class="icon">✏️</div>
  <h1>Request Script Edit</h1>
  <p class="sub">Describe what you'd like changed. The pipeline will revise the script and notify you when it's ready.</p>
  {error_html}
  <form method="POST" action="/review/edit?token={token}">
    <textarea name="edit_instructions" placeholder="e.g. Make the hook more dramatic. Add a section comparing power levels. Remove the part about the arc reactor." required></textarea>
    <button type="submit" class="btn btn-submit">✏️ Submit Edit Instructions</button>
  </form>
</div></body></html>"""


_HTML_EDIT_SUBMITTED = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Edit Submitted</title>
<style>
  body{font-family:-apple-system,sans-serif;display:flex;align-items:center;
       justify-content:center;min-height:100vh;margin:0;background:#fffbeb}
  .card{background:#fff;border-radius:16px;padding:40px;text-align:center;
        box-shadow:0 4px 24px rgba(0,0,0,.08);max-width:420px;width:90%}
  .icon{font-size:72px;margin-bottom:16px}
  h1{color:#d97706;font-size:26px;margin:0 0 10px}
  p{color:#6b7280;margin:0;font-size:16px;line-height:1.5}
</style></head>
<body><div class="card">
  <div class="icon">✏️</div>
  <h1>Edit Instructions Sent!</h1>
  <p>The pipeline will revise the script using your instructions and email you when the new version is ready.</p>
</div></body></html>"""


_HTML_REJECTED = """<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Script Rejected</title>
<style>
  body{font-family:-apple-system,sans-serif;display:flex;align-items:center;
       justify-content:center;min-height:100vh;margin:0;background:#fef2f2}
  .card{background:#fff;border-radius:16px;padding:40px;text-align:center;
        box-shadow:0 4px 24px rgba(0,0,0,.08);max-width:420px;width:90%}
  .icon{font-size:72px;margin-bottom:16px}
  h1{color:#dc2626;font-size:26px;margin:0 0 10px}
  p{color:#6b7280;margin:0;font-size:16px;line-height:1.5}
</style></head>
<body><div class="card">
  <div class="icon">🚫</div>
  <h1>Script Rejected</h1>
  <p>The pipeline will generate a completely new script on a different topic and email you when it's ready.</p>
</div></body></html>"""


__all__ = [
    "create_review_token",
    "get_review_urls",
    "register_media_file",
    "start_review_server",
    "unregister_media_file",
]
